// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmkcyuwurxadufassayc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhta2N5dXd1cnhhZHVmYXNzYXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjU2ODUsImV4cCI6MjA3MTAwMTY4NX0.xRyQUzLmKy9jEUSSN4mH-5jLaD3rypde8VxQWmHxSAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});